name: GameCI Template 🎮

on: push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

jobs:
  checkLicense:
    name: Check for the Unity license ☑️
    runs-on: ubuntu-latest
    steps:
      - name: Fail - No license ☠️
        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
        run: exit 1

  buildWebGL:
    needs: checkLicense
    name: Build for WebGL 🖥️
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-build-WebGL
          restore-keys: |
            Library-build-
            Library-

      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      - name: Upload artifact to GH
        uses: actions/upload-artifact@v3
        with:
          name: build-WebGL
          path: build/WebGL

      - name: Push Build to branch build/webgl
        run: |
          git config user.name quangnguyen11
          git config user.email quang888@gmail.com
          git checkout build/webgl
          git add build
          git commit -m "build webgl"
          git pull
          git push

  # pushCode:
  #   name: Push code to branch build/webgl
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Before checkout
  #       run: ls -al

  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       with:
  #         ref: master

  #     - name: After checkout
  #       run: ls -al

  #     - name: Push code to branch
  #       run: |
  #         date > generated.txt
  #         git config user.name quangnguyen11
  #         git config user.email quang888@gmail.com
  #         git add .
  #         git commit -m "build webgl"
  #         git push --set-upstream origin build/webgl

# install --directory ~/.ssh --mode 700
# base64 -d <<< '${{ secrets.SSH_PRIVATE }}' > ~/.ssh/id_rsa
# chmod 600 ~/.ssh/*
# git init
# git remote add origin "https://quangnguyen11:$GIT_TOKEN@github.com/quangnguyen11/game-ci-test"
# git config user.name quangnguyen11
# git config user.email quang888@gmail.com
# git checkout -b build/webgl

#   git init
# git remote add origin "https://quangnguyen11:$GIT_TOKEN@github.com/quangnguyen11/game-ci-test"
# git config --global user.name 'quangnguyen11'
# git config --global user.email 'dquang888@gmail.com'
# git checkout -b build/webgl
# git add .
# git commit -m "Build WebGL"
# git push --set-upstream origin build/webgl

#git remote add origin git@github.com:quangnguyen11/game-ci-test.git

# deployPages:
#  needs: buildWebGL
#  name: Deploy to Github Pages 🚀
#  runs-on: ubuntu-latest
#  steps:
#    - name: Checkout code
#      uses: actions/checkout@v2

#    - uses: actions/download-artifact@v2
#      with:
#        name: build-WebGL
#        path: build

#    - name: Display structure of root files
#      run: ls -R
#      working-directory: build/WebGL

#    - name: Deploy 🚀
#      uses: JamesIves/github-pages-deploy-action@4.1.4
#      with:
#        branch: gh-pages
#        folder: build/WebGL
